### ISSUE TITLE
Official logo

### ISSUE THREAD

**Issue by MatuxGG** [Lunastellia/Challenger-Among-Us#2]
Hello,

I don't know if you know Mod Manager but if you don't, it's a little software I made providing easy access to mods and it's currently used by many people.
I'm currently developping a new major version and one of the newest feature I added is linked to external mods that already embed their own launcher. Here is the interface of this section :

![image](https://user-images.githubusercontent.com/12508157/115878452-db5f7980-a448-11eb-8ae5-807bdaeef71c.png)

There is an open beta version available here if you want to see it globally : https://mm.matux.fr/mm4/ModManagerInstaller.exe

And here is my "issue". I can't find any official logo for your awesome app. Is there any official one released yet ?

Thanks in advance and thanks for your great job, your mod is really cool so far :)

(Note that if you don't want me to include it, you can just tell me and I will not add it without asking why or anything)

**Comment by Lunastellia** [comment]
hello and thanks for contacting me, first of all i want to apologize for
the quality of my english i use a translator.

Thank you for your positive feedback on my Challenger mod,
Currently I use a temporary launcher while waiting to create mine allowing
later to apply lang, map customs and additional mods in order to satisfy as
many people as possible,
so the version will change soon but no worries you can use this logo
(tempoary too^^), I will send you the link to the new launcher when it is
available !

Thank you, Lunastellia, - Oriana
French Multigaming and Esport Community

![challenger](https://user-images.githubusercontent.com/79289200/115961465-bcc7b400-a516-11eb-967d-d3ca20873b59.png)

**Comment by MatuxGG** [comment]
C'est marrant, on aurait du commencer par la. Je suis Français aussi ^^

Merci beaucoup de ta réponse en tous cas, c'était très compréhensible ;)

**Comment by Lunastellia** [comment]
Ahaha effectivement c'est plus simple du coup :)

**Comment by Lunastellia** [comment]
@MatuxGG Si tu peu me contacter par Email **lunastellia.oriana@gmail.com** j'aurais une demande à te formuler en privé ^^

**Comment by MatuxGG** [comment]
Très bien
