### ISSUE TITLE
Excuse me, how to solve this problem?

### ISSUE THREAD

**Issue by ponyzerteal** [Lunastellia/Challenger-Among-Us#8]
I'm a Chinese player. I read the related introduction of your mod and found it very interesting. However, in the process of playing, we had the problems shown in the figure below, hoping to give a solution.
![}F3ZA2T$8ZJW8JAYGTEGX(2](https://user-images.githubusercontent.com/97593043/186382785-b935850a-c96e-4052-b416-2f15fbfa1407.png)
By the way, it would be better if you could send me xlsx files to translate your mod.

**Comment by Lunastellia** [comment]
Hello, to work Challenger requires Steam, did you have your steam.exe open? in principle this display bug is due to the fact that the game cannot find your Steam information.

Regarding the translations I am developing challenger 5.0.0, I am modifying a lot of content and the translation system when that will be I could send you the translation files for you to add your language and it will be integrated into a next patch?

**Comment by ponyzerteal** [comment]
![image](https://user-images.githubusercontent.com/97593043/186713923-10a8a709-f60b-4f60-a558-da3b9deca37b.png)
I'm pretty sure that my steam is running, and it's not just me, but also my other friends.

**Comment by ponyzerteal** [comment]
I use modmanager software to install challenger.

**Comment by ponyzerteal** [comment]
In version 5.0.3B, this problem has been solved. Can you give me string files for me to translate into Chinese?

**Comment by Lunastellia** [comment]
hii , I don't use a json file or xlsx fiel for the translation it's a little more complicated ^^ there is a lot of text and adding a language requires a lot of work ^^ more if a translation work is beginning it will have to be updated regularly.. 
I'll create a specific file to translate that I will report in the code but it will take me a little time
